# Generated by Django 5.2 on 2025-05-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
    ]
