# Generated by Django 5.2 on 2025-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="uid",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
