# Generated by Django 5.2 on 2025-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_token_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default="", max_length=255),
        ),
    ]
