# Generated by Django 5.2 on 2025-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_token_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(max_length=40),
        ),
    ]
