name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:slim

# It lets us cache pip-installed packages
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
      #Make Firefox run headless
      MOZ_HEADLESS: "1"
      HOME: /root
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      # "setUp" phase, before the main build
      - name: Show python and pip versions # for debugging 
        run: |
          python --version
          pip --version
    
      - name: Create and activate venv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m virtualenv .venv
      # Main build
      - name: Main build
        run: |
          pip install -r requirements.txt
          # unit tests
          python src/manage.py test lists accounts
          # (if those pass) all tests, incl. functional.
          apt update -y && apt install -y firefox-esr
          # for debug purposes
          firefox --version
          geckodriver --version
          pip install selenium
          cd src && python manage.py test
