name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

# It lets us cache pip-installed packages
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      # "setUp" phase, before the main build
      - name: Show python and pip versions # for debugging 
        run: |
          python --version
          pip --version
    
      - name: Create and activate venv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m virtualenv .venv

      # Main build
      - name: Main build
        run: |
          pip install -r requirements.txt
          python src/manage.py test lists accounts
          pip install selenium
          cd src && python manage.py test
